### ISSUE TITLE
Showing <br> (Soft Break / Forced Line Break)

### ISSUE THREAD

**Issue by jensschnitzler** [grommasdietz/kirby-hidden-characters#1]
Thank you very much for your great plugin!

I tried around with also making the `<br>` visible in a way InDesign would. I tinkered around and I don't know exactly how it works and how well it performs across different browsers, but here is what I came up with: [https://codepen.io/JensSchnitzler/pen/MWqGpVp?editors=0100](https://codepen.io/JensSchnitzler/pen/MWqGpVp?editors=0100)

If you consider it good enough, would you want to add this to the plugin?

As you can see I created the glyph just through two borders. Alternatively one could add the glyph as background-image.

**Comment by grommas** [comment]
Hi Jens, thanks for your feedback and thoughts. I already tried out some possible solutions for visualising line breaks without luck. Your code works fine in Chrome and Opera, but not in Firefox and Safari (MacOS). Are you working with MacOS or Windows? I can implement a new glyph into the font and update the corresponding CSS code the next days though. Would you mind testing your solution with a custom glyph and see if this works for you as well? 

````scss
@font-face {
  font-display: swap;
  font-family: 'hidden-characters';
  font-style: normal;
  font-weight: 400;
  src:
    url('data:application/octet-stream;base64,d09GMk9UVE8AAAccAAsAAAAADNwAAAbRAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAADY0IIoFWIxIGYACBBAE2AiQDgSAEBgWFIQcgGxQMo6ERbBwI5PGc7K8POLnEyhGKqZK7Vu2YiUuOjZ8t2H0Eh0FlSRO+QGlfo4o4cD/ZfhyvA0rq/h+s88EGz7wHEMpC2ypTX4xbXMsHZSIfWDgaEBRSuOMkAxZqSsyL8fDP/v7/59q4+zxASEKSkzqYoAgmML2u0cH/fS5xauLUcqfk3JGKLiGNCOgVv9oFQP6Hg6cE7P3/rbW68u8OsU/j9SmdSRkNcWdOP+I+LO4tEeLNIpZMEiSIRGqjRCKxs4xNhxUF2n9PgEigxs0bTYzWYrEMipQRJB4eo3/KFFWsHILf/IKJB6dPnuz/E5biTzt/jgqelXDH7J/ZlvRL1eyfN+KgVlxoml/O/4qo8Vd8rSt/TcdEKKmhvmba6qK3QUaaYLp5llpjnR12OeiUM66646l3Pvnq/6gaNDSOXbhRO/ao8OPXYle9WxFnE6dlUsAACwBM8KAAHxzTFcXhxhCAbZdas+XSSXirAhZiydrIwruXcXmWYtGNMvWGNOFKGYzDeK1TRdN1wFs88Cbv8QXv8042Vy5uffn+APE2V5aZ5K9Z/xp9/xrWe9aWp9x2zG0Xep5nzjoq81wxrCLKe+rO+ngERZYBRR+EgZCRntGO7tweYP1Q1WB+6rF2geZVqtesrQwmi/XudLW8KKs2dg7OLq9vH23ISnp++7dDR46dOHXmXPjpRxfCHg+qeoRTT6qZt/Kyn23t4kNFnD89GEAbhlLsFUEXBlJcF0TBEkLFuZiYwvzBWGoNCm74R3zpKN9rwDL90jL4tpW4rYj/b2EXWuhki1mzNdT98xzbWMXglBhChYYChVrGzjjAuMi413jW+F5ykQKkWClbaiF1kIZKI6XZ0kppm3RYuiDd5Jo3NetzPGh5jGjC0E9TMsBPUXkORJX1DvNmLJqaoQa2Y7BKk9fI4EfiRR15PAkSc+XpJEr0l+GN/WveP9H4hc8tbHrB67R4T1yl6U3ksk1cYxvAT4aj43n/6fCWdEM/GYfxtWy66KNMGi/jZVJXrf8qvab4hLe9qQrF9uBFnnJ/GZ6SBOE1eZNnqbgLyXrwkXEBuccNlDnN8B6YSh5zJ8jyJsmi5CmAF00ZssFbBnSdTGGQ/xlJuqOPDMMJnwg+rFnR3SEc9CEqvOIFLBcSjinPN+0H4wU3MF2+/gYqOU9VIBUDoQr2xPFYFd0xf7TbJIhTpkyBL2aa/fAm2LmA5VFOiPtEJb5dI78ablihsF7WNJRsP4i67N7RwzduNDyckdmgcV7escZ33dUbHhT9+RWWQJu379Cs2fYO+93hhH0CbdYhpW7rcMBdhU4vvzhsfnkDGSLIfJ32iNT0pt6Ua1H0Jt3sKxIWSaGAP5NVCPKggZwwpCdCVQJBYrRdxUcrjVggaq/ND3KdLSu7BzEaGY55BGdjY8zBibjeAodPgYaYDrNd4Ln1JtOsI3W9osJHD6pvsYmncZQQcRdiZYnMOBpPPnOpeg0GDUjkAan9PaiYqGddk0R9juPNF3MY+PE56LeZlFYh8ZU4EOIicCLETcbnmm2iqXrrzJlbt2qdycmpVct+1plat9zNxWIU08gFqKpZExQV31iDGMZZYzZ6QAXTmzfgmANRb9BktjqiotAEr3gTBY2WVrlzc9uBAx22NTMbqIvqOBqGH32BzARDiiHDkGOowFBgKGGohKEyhioYqmKohqE6hhoYamKohaE2hjrFMevPWQ/10QAN0QiN0QRN0QzN0QIt0Qqt0QZt0Q7t0WEFRK3w2rhLWZb8bzwlV8p7Z29x2j88eWVtooFC9pPWdKt5UxZM90TLD4pz/1O9uB6fx56OrH9+mRA3CdK9LE5r3HVltrDe4rTF2RfcaFmtZY+WK4uynCljRbxtQ9ny/iMt9yVklFZe4+3IpSpkqqusikIl1T7v0ixO9raI7Xn61ugzK2qk/JKWGH3v06pLfNf/lSsuEFxcEBtsXVVcX1VlSY1RdNaIcXnH9KSxSYYL8ez/z7astH3ZtXKqsVPlVkkLtxMGxlyd2+krR8vyfumq45RPxJU7jVxt87ztr2o+1onMpCNquEd4W6h1Qt0SxW1bDplGGsaUh6W9wKw4eZJUZJWw1CqKhdYeskR171nKuPafEcywGAniYVK+H2Mt4r+XG8/iN/4Qh5mtfaDpPFZiWcD08jcwOWrX5jtR5K39Sap/wAS2zjTTUZmbVykGdUR5L9fp45GZIoNG8FUbfeBlO/pyxKpKz2hhsI/WbMQCUYUWK1JGuEY+hmH/lJUOT12AOT9y27nYD9eNsCl30BC2OeNBwJeelzXHsv06Es5q1+Y7UUp3lJht7mh1m5HTo+8=') format('woff2'),
    url('data:application/octet-stream;base64,d09GRk9UVE8AAAi0AAsAAAAADNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDRkYgAAADnAAABKEAAAaIYXwq00NPTFIAAAhAAAAAXgAAANYA3AO+Q1BBTAAACKAAAAASAAAAEs0AzNxPUy8yAAABsAAAAE4AAABgd4vdy2NtYXAAAAMoAAAAXwAAAIRBoEKXaGVhZAAAARAAAAAwAAAANiNtYWdoaGVhAAABkAAAAB8AAAAkDg0E62htdHgAAAFAAAAATwAAAKB3zAC+bWF4cAAAAQgAAAAGAAAABgAoUABuYW1lAAACAAAAAScAAAKh0Rtm83Bvc3QAAAOIAAAAEwAAACD/NgBkAABQAAAoAAB4AWNgZGAA4dnrNxrE89t8ZWDmYACB+8w80TD634Z/QuwLWBcDuewMTCBRACLzCoB4AWPuZ3BhcmBYwHj83zsOBoYEEGaBYlYuBimGCf+TmBIYNjAxMFgwhjBoAdVyMSr8b2BaxdDLwPD/AJBdxcDwbwPLCbB6OWqbBwDUKybdAHgBY2BkYGBf80+IgY+D4d+GfxvYFwBFUIEGAJCcBgcAeAFjYGH6xziBgZWBg9WI5RwDA8NsCM10miGFSYYBCTQwMDALIPFDvcP9GA4wKDxgZJ/3T4iBj30N4zugMCNIjsWMdTGQUmBgAACg2A2gAAB4AZWQRZpTQRRGT9xt1j17X8YtkWEm7d64e6Ti+gTbB4tgCdiQdbAC9sDlcaFd+MpO1S8RIMdnAgCyF0A5SIyCcph55pQjQmXlqPAuIQLhBPCMunKAIt+Ug2T5oRxii5/KYSqBqnKEUsAoR4U/KCcoBr4r5491FpDOnV6rZcbWerdu15uusZ07puMN6/aZd0uFB8K9ydgqL5VKpdrW5up+z/19+RM48i+qn49YVCjJqghtYzNhJKOOg8UGPQwu732twR2WhFYZyrCwRe3QFd3xbwZHls1rDC1x7ojekmEYi74uzjq2rCau73O4g6GDx9BXyixR8keN++zzkBtCx1vO61g81XL1p1qnEg/0vcfEzxz/Hltsssq+aC6q/O83uvpf/QU0VHIAAHgBPcjFgcIAEADAieCH8480QEec/s4oiQZoCakknqzvIESEQzWDZsfO2FRZudTFNV2mx/TtERTFICp5fSiK4ln8FF/cn6Q7AWCOHIxExmKryhYmZpam1k2G1iUudRKvAHgBY2BmAIP/xgwpDFgAACUuAZoAeAGtlHV427gbxyWndjYlTzpyR77WZRil4fHK7eHvxszp0vHSjpmZmZmZmZmZmenodyQl8kCu16fL/xf66vOiJL9PIAjiAISwbGZO+/burimeNt427fLc3txKdd0denZu41Wd1UOXgMxhk8ePL1CjngQDkgRJMkfKBNHpRt3vxiD6Qhkm6ZdI/HLeZw72OYuv9eESII6VB0VAMAgB34AoUAFYQFVQB2SAH0ED0By0Ax1BHugPhoEpYAFYB/aAU+AGeAb+AB+hEZaDcdABU2Fd2Bp2hYPhRDgfXoSvenbNsZjt6fliTtTEqolZE4smTk2SNHFpYtfEwYS5viRU1cSmSXK+WNJzu2Xnefp297i7MkOaVp1JYuWu3fLau7Mrd27T1+0153Zv0879Zf1la18RCw8gawCZA8gSQM4ASgogVwDZA8hRSCwtsEPVALIFUPLXZCk4Q+EdFLrVqwiggiM2j2vXPF5m2RY5w9utS5c2uXJqjjuvn5zRtm5lOalzZ9mb08GTlyt73bluby93+8ra3MmFgycXDB6A6nt0NIiDkDeYipUIKRcaER1XsYrVWb12SsZ3PzVo3LR56/aezt28vfoOHDpy7MSpM/H/Y9BcvENGJrkKCmdv0jYi/+vrHIUURyzaG4eaVELUa0Zz4xFdlYCwsSJSTtnYujJTO/IlVGDB0ei/q9Rnkf/cIvzbRiF0ifOTsehcIxpvNEhFQClySlxbEpTlAAQCKAPiQSWwCAbDPnAe3AlPwtdceS6Os3MpXGvOww3khnLTuaXcJm4/d4a7SqRIZPDPkNFHm9JcpDGSvg6O0ZsIsyiaxXdDNYhWZMD/o9kiXibxK3gcIziV+vxoIUGZyU8WLEpvHr8IeU56M/iFzGSOJ6S+GkWXSf7m/Id1RBLX4BgeHxxNek/GL4WuNIang8hKcbKSpx83mqfnBdXv/zPfo7yj1yORCX8XgiOEhySWxw8Fl8IkUnik0lxhNY7i6RzhFgE8nsQokqcThfukLE8jheoKk4caRWg0gZWN5PEEIUkBPB0qdKNRPB4skLE4SmShNwlQW5jwM5IppmHXIf3jdbsxPBOKdecvv8DFy03U45o0HpekPehoWoqG0YzhoeOwQz9hAo910+9excHlsfFeasWwsXpndtOY/4XSolkNkydRrsgbpYF46+D+K1ea7K+T1LhZevqhZjfDTFdkRGPJBdGFWnXwtGy52bM7DB8JcaGWHkabPHvCTLgj+wMUZ39szGOzMNvfmE+U/C0iEZEsSJ2mX6kgJiKcSR7xJpwgo3giiFQlXErACcpwnECGq2uaqbAIspf4xUUfbmGbJAym6QKdTpvRVDqWbZcOnoCb0Np4enn82HdVlHxD84P0JvxWRv4NQU7kQGw3bB4+bAhyIKcKUayf/38ibiwkIhPuzUZlrD+ZjYp/BhsVGqPMEHEMmUFjBBOuxZzqltVtULYdti3KtqeuDUFWZLp24sS1a3VPpKbWrZuaeqLutTDDd8owURLO4FKSz6U30Re+BJE6fDbsYFvSvXiBdVhneUF1BqqzWKiO6l5YsM6wZ9OmPXs8m1oaPgO4xHokAAAAeAEtwQNiAwAABLDcbK82f9p394YEX3jByRfI/4uOy46rjuuOm47bjruO+46HjseOp47njpeO1463jveOj47Pji98Y4AhRhhjgilmmGOBJVZYY4MtdtjjgCNnp6sEmwAAAAAAAQABAAEAAAAOAADMzMz/AAA=') format('woff');
  unicode-range: U+0020, U+00A0, U+00AD, U+2000-2009, U+200a, U+202f, U+205f, U+e000, U+e001;
}

p {
  font-family: 'hidden-characters', Arial !important;
}

br, br:before, br:after  {
  content: '';
  position: relative;
  width: 1em;
  height: 1em;
  display: block;
}
br {
  display: inline;
}
br:before {
  position: absolute;
  inset: 0;
  
  content: '\e000'; // has to be replaced by a corresponding glyph
  // glyph:
  // width: .6em;
  height: 1em; // .25em;
  // border: 2px solid rgb(50,50,255);
  // border-left: 0;
  // border-bottom: 0;
  // margin: .2em;
  // margin-top: .5em;
}
br:after {
  width: 0;
  height: 0;
}
````

Even though Firefox and Safari are currently not supporting to hack around the br-tag on MacOS, I can implement this solution for the other browsers after testing!
