### ISSUE TITLE
Showing soft hyphens

### ISSUE THREAD

**Issue by medienbaecker** [grommasdietz/kirby-hidden-characters#2]
I mentioned your great plugin in my recent article about hyphenation without checking if it actually shows soft hyphens. Now that I got around to trying it out, it doesn't actually seem to work 😅

While there seems to be a `softhyphen` glyph in the font file, the unicode range does not include `U+00AD`. Adding that manually does however not help either. Do you have any idea how to show soft hyphens, ideally as a vertical line like the markdown field does:

![CleanShot 2025-01-03 at 12 25 45@2x](https://github.com/user-attachments/assets/ccd3ab0c-aa45-47d0-8190-6b643ea61c17)

Thank you!

**Comment by hansipete** [comment]
Such a great plugin, thank you. I'm also trying to render soft hyphens and also tried the obvious and added `U+00AD` to the @font-face unicode-range.

That rendered at least some other character in there. @medienbaecker maybe it also did for you, as I had to zoom in a lot to see it.
![Image](https://github.com/user-attachments/assets/00301a47-9109-4185-b10b-1f6826e57c78)

**Comment by medienbaecker** [comment]
Ah, I guess I've missed that. Thanks for checking, @hansipete!

So the glyph in the font file has to be adjusted I guess.

**Comment by hansipete** [comment]
I tried to further investigate and build myself a custom font that has (what I think) all the neccessary glyphs but stimmt it never showed the one for soft hyphen.

Read a little bit about the topic and it might be that it's just not possible to display the softhyphen in web browsers (these days). Beeing "control character" it does not even need to be present in a font to "work". And it seems many applications just don't worry about displaying it in the first place. At least that's my result from the discussions over here: https://typedrawers.com/discussion/comment/26592/

Too bad :(

**Comment by grommasdietz** [comment]
There is a similar problem with the visualisation of `<br>` tags. Ideally, both should be visually represented, but achieving this seems to require custom rendering in ProseMirror—likely by wrapping them in a `<span>` element. Unfortunately, extending ProseMirror's rendering logic is currently beyond my expertise. If someone with more experience in this area could offer guidance or collaborate on a solution, I'd be happy to integrate it.

**Comment by grommasdietz** [comment]
Ah, I just saw that you’ve already found a solution, @hansipete. If you're open to it, we could integrate it into the plugin — with proper credit, of course. I’ll take a closer look at your implementation — perhaps we can adapt a similar approach to also handle `<br>` tags and address both issues together?

**Comment by grommasdietz** [comment]
Your solution provides better support for coloring hidden characters consistently across all browsers, @hansipete. In the current version, we need to fall back to a non-colored font in Safari; otherwise, the rendering logic incorrectly applies the custom color to the first letters of the following lines.

We could limit the plugin to support only Writer fields and render all hidden characters directly in the overlay. To keep the regular expressions minimal, we could still use the custom font for all whitespace characters, additionally handle soft hyphens and line breaks and wrap all of them in custom tags for same color styling.

I've put together a first draft. If you're interested, feel free to open a PR to contribute. I'm happy to credit you in the README and/or invite you as a collaborator.

src/index.js:

```js
import './styles/hidden-characters.scss';

function renderHiddenCharacters(input) {
  return input
    .replace(/<br\s*\/?>/gi, (match) => `<break></break>${match}`)
    .replace(
      /\s|\u00A0|&nbsp;/g,
      (match) => `<space data-character="${match}">${match}</space>`,
    )
    .replace(/\u00AD/g, `<shy></shy>\u00AD`);
}

window.panel.plugin('grommasdietz/hidden-characters', {
  use: [
    (Vue) => {
      Vue.mixin({
        mounted() {
          if (this.$options.name !== 'k-writer-input') return;
          this.$overlayEl = document.createElement('div');
          this.$overlayEl.className = 'ProseMirror k-text gd-hidden-characters';
          this.$overlayEl.setAttribute('aria-hidden', 'true');
          this.$overlayEl.inert = true;
          this.$overlayEl.innerHTML = renderHiddenCharacters(this.value);
          this.$el.appendChild(this.$overlayEl);
        },
        watch: {
          value(newVal) {
            if (this.$options.name !== 'k-writer-input') return;
            this.$overlayEl.innerHTML = renderHiddenCharacters(newVal);
          },
        },
      });
    },
  ],
});
```

src/styles/hidden-characters.scss:

```scss
@font-face {
  font-display: swap;
  font-family: 'hidden-characters';
  font-style: normal;
  font-weight: normal;
  src: url(data:application/octet-stream;base64,d09GMgABAAAAAATcAAoAAAAAC7wAAASSAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmAAdAqMOIl2CywAATYCJANUBCAFhCQHgWQbnwnIHoVN2V0UR5hMQpmM70GdCOL3+9/skS+GmCSxSMKTNpekCW5D4quEShLxqtoIUY9yrtkmLZDgkusTMS+iovc29Qr///uxmbh7/+Chet0jIXKEROgwa4tvKhJd0zxpEo1bEktqbStp08wtfVwOMZmYuIGSR6NJ1VFV8XPAWdo8vRCWJMH0pQG5P/zSupWeDnAE1FeMbeAfP3C3z8U7IKAsoI9iPEBCxmCYgAq3Oas/3rqrxhuiMIqklKjAB9j/JQ1QBaBeQwDqS+9/vb88e5ke6CVVm6wYSIAgPoAhADO9yngG0jhGVdgoCcmJyhzm6BBbTOLkZOPEHcZLfIEkzslTEQDAicIZfDw3Xv4yxus3ntevI1T8+hpR89JNkEDX31wna19dBWjcnl5YAl1x8zUqLq+FoivE7fTQSNKf8PEi7qvr3PmA95e8UrmQ87uNuEAhUAgUSBh4p97ZzZH82tLAG2llKOFJ+noq0otLQ7oRSsKXMyJTGOr6+O1ekMshs6aXlfRc0luf5EdcguPz+Hu3U7gDt1z3iPqKXJJGMDzGEZ17UY43t87lRQI48WQNm2wik6h5HXRKygWVhok8gAuXG2fwHEdH4o7pXiq28gauRjQl+jhvWT2/hCC6K4wgzMercdLlSNyU3foKt7R4PuLgep2c2pjllCMLY3V1L0NL2xwEf7VhptJmhYZGexAYcnaV1bS/E2cterDbsJPARcYtxnu9qwrSAFrcUi8479O9Pc9gXh8NDR8tLRCR2DEdWn2rM/nQ2G02zFVU6Oag3UzV3ubSa8nmV5YFnwO7TxZZLZbHHK1ICf+RDf9eAf+V/6wr4SRx5VZDWBWe8vQ9Zis0lG51Nqq15s3DuVV6mWxGNb/iDVdZD+WTlSG5+h6zqvWWyXx7hnmX6QLBZzYGRn3XfC8S2KtlMGCx+es5Tf5H/Z9jCS3Qmp9XAqd4ELR/bGDhDoGCc1GZW2kpK/PwfFzBCrSdGBKo4ALpVFjRei3R+JYV+0Oy4YdjWYMKLGis/1Oi4ZdNLF6dT3dpaYQ9a1VLg+VEViyrCPS/XVru5QACiUNXv38M5NH/yo6xA/x0dVula2dLYPM/frah+g5ol0Yktp/7uvM7wGbHz/YhQf0hed7mOPKE6Y2wwIQOoOTkhMC2CbWjT0KqS3nG0nIkLEnJtTEftIJxCCXYSSEZi43CvqrbGciicADrAWcOE/mZkz7HzdkSdeZijkvmamTg5jazQjqisw4dzD3mRNTA/nNzB3zXNIynSpkqdRQrKRLFixcsFcVctHBpcuqfE8KFIoqJOHEoKaJFipImNRcRTiw8IkOMCOv1HGvRwoQJl4BiJkqwFMFCpYkZqVxQFSldXG2VKkXKzl/0uLPlyYHeDN2LQyigtysORUkxHnVZ0RL7h+2hT9ft6d1FRHGqNEkZupScwZG9DArCshSF1ibR2G7/q0GYnxgC5KAhDOGIjhiIDbEjDkQgEnEiLsSNeBAv4kP8SAAJsqUnRCsrmyhT4G+Cg2qojCqojhqoiVqojTpowjOVqlpyNaIt1ggEKqNKpCo=)
    format('woff2');
  unicode-range:
    U+0020, U+00A0, U+2000-200A, U+202F, U+205F, U+E000, U+E001, U+E002, U+E003;
}

.gd-hidden-characters {
  pointer-events: none;
  position: absolute;
  width: 100%;
  height: 100%;
  color: transparent;
  opacity: 0.4; /* equals the placeholder color */

  p::after,
  space::before,
  break::before,
  shy::before {
    font-family: 'hidden-characters';
    font-weight: normal;
    color: var(--color-text);
  }

  p::after {
    position: relative;
    display: inline-block;
    width: 0;
  }

  p:has(.ProseMirror-trailingBreak):after {
    margin-top: -1.5em;
    position: absolute;
  }

  p:first-child:last-child:has(.ProseMirror-trailingBreak):after {
    content: '';
  }

  break,
  space,
  shy {
    display: inline;
    position: relative;
  }

  break::before,
  space::before,
  shy::before {
    display: inline-block;
    position: absolute;
  }

  break::before {
    top: 50%;
    transform: translateY(-50%);
  }

  space::before,
  shy::before {
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }

  p::after {
    content: '\e000';
  }

  p:last-child:after {
    content: '\e001';
  }

  break::before {
    content: '\e002';
  }

  space::before {
    content: attr(data-character);
  }

  shy::before {
    content: '\e003';
  }
}
```
